#!/usr/bin/env zsh

alias pip-remove="pip freeze | grep -v -- -e | while read file; do pip uninstall "$file" <<<y ; done"
alias bubu="brew update && brew upgrade"

alias pycharm="/Applications/PyCharm\ CE.app/Contents/MacOS/pycharm"
