#!/usr/bin/env zsh

alias pip-remove="pip freeze | grep -v -- -e | while read file; do pip uninstall "$file" <<<y ; done"

alias wakeup="wakeonlan -i 10.10.1.255 9c:b6:54:09:2e:2b"

alias ls="exa"

alias docked="autorandr docked"
alias undocked="autorandr undocked"

alias restore="nitrogen --restore"

